# https://developers.home-assistant.io/docs/add-ons/configuration#build
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bullseye"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bullseye"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bullseye"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bullseye"
  i386: "ghcr.io/home-assistant/i386-base-debian:bullseye"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Nexus AI"
  org.opencontainers.image.description: "Autonomous AI assistant with memory and smart control for Home Assistant"
  org.opencontainers.image.source: "https://github.com/nexus-ai/home-assistant-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
