---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11
  i386: ghcr.io/home-assistant/i386-base-python:3.11
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Nexus AI"
  org.opencontainers.image.description: "Intelligent AI Assistant for Home Assistant with advanced pattern recognition and automation"
  org.opencontainers.image.source: "https://github.com/yourusername/nexus-ai-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  PYTHON_VERSION: "3.11"
