# https://developers.home-assistant.io/docs/add-ons/configuration
name: "Nexus AI"
version: "0.1.0"
slug: "nexus_ai"
description: "Autonomous AI assistant with memory and smart control for Home Assistant"
url: "https://github.com/yourusername/nexus_ai"
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
homeassistant_api: true
ingress: true
ingress_port: 5000
panel_icon: "mdi:robot"
panel_title: "Nexus AI"
map:
  - config:rw
  - ssl:ro
  - media:rw
  - share:rw
options:
  log_level: "info"
  openai_api_key: ""
  use_local_model: false
  local_model_path: ""
  memory_persistence: true
  data_directory: "/data/nexus"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  openai_api_key: "str?"
  use_local_model: "bool"
  local_model_path: "str?"
  memory_persistence: "bool"
  data_directory: "str"
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web interface (Not required for ingress)"
webui: "http://[HOST]:[PORT:5000]"
hassio_api: true
hassio_role: "default"
